# LinacSimPy is an interactive model of a medical linear accelerator (LINAC)

# © 2025 Alberta Health Services, Medical Physics

# This file is part of LinacSimPy.
# LinacSimPy is free software: you can redistribute it and/or modify it under the terms 
# of the GNU General Public License as published by the Free Software Foundation, either 
# version 3 of the License, or (at your option) any later version.
# LinacSimPy is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with LinacSimPy. 
# If not, see <https://www.gnu.org/licenses/>.

# This material is intended for general information only and is provided on an "as is", "where is" 
# basis. Although reasonable efforts were made to confirm the accuracy of the information, 
# Alberta Health Services does not make any representation or warranty, express, implied or 
# statutory, as to the accuracy, reliability, completeness, applicability or fitness for a particular 
# purpose of such information. This material is not a substitute for the advice of a qualified health 
# professional. Alberta Health Services expressly disclaims all liability for the use of these 
# materials, and for any claims, actions, demands or suits arising from such use.


from PyQt5 import QtCore, QtGui, QtWidgets
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:

    def _fromUtf8(s):
        return s


try:
    _encoding = QtGui.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)


except AttributeError:

    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8('MainWindow'))
        # commented out statements that lock window size
        # MainWindow.resize(800, 630)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        # MainWindow.setSizePolicy(sizePolicy)
        # MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        # MainWindow.setMaximumSize(QtCore.QSize(800, 630))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName(_fromUtf8('centralwidget'))
        # define window layout
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName(_fromUtf8('gridLayout_5'))
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName(_fromUtf8('gridLayout'))

        ## beam on frame
        self.frame_BeamOn = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_BeamOn.sizePolicy().hasHeightForWidth())
        self.frame_BeamOn.setSizePolicy(sizePolicy)
        self.frame_BeamOn.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frame_BeamOn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_BeamOn.setObjectName(_fromUtf8('frame_BeamOn'))
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_BeamOn)
        self.gridLayout_7.setObjectName(_fromUtf8('gridLayout_7'))
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8('gridLayout_2'))
        self.label_4 = QtWidgets.QLabel(self.frame_BeamOn)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8('label_4'))
        self.gridLayout_2.addWidget(self.label_4, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_BeamOn)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8('label_7'))
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.pushButton_BeamOn = QtWidgets.QPushButton(self.frame_BeamOn)
        self.pushButton_BeamOn.setCheckable(True)
        self.pushButton_BeamOn.setObjectName(_fromUtf8('pushButton_BeamOn'))
        # change button color depending on state 
        self.pushButton_BeamOn.setStyleSheet("QPushButton"
                             "{background-color : green; font-weight: bold}"
                             "QPushButton::checked"
                             "{background-color : red; border: none;}"
                             ) 
        # new tooltip
        self.pushButton_BeamOn.setToolTip('Ctrl-B')
        self.gridLayout_2.addWidget(self.pushButton_BeamOn, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_BeamOn)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8('label_6'))
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.comboBox_Energy = QtWidgets.QComboBox(self.frame_BeamOn)
        self.comboBox_Energy.setEnabled(False)
        self.comboBox_Energy.setObjectName(_fromUtf8('comboBox_Energy'))
        self.comboBox_Energy.addItem(_fromUtf8(''))
        self.comboBox_Energy.addItem(_fromUtf8(''))
        self.comboBox_Energy.addItem(_fromUtf8(''))
        self.gridLayout_2.addWidget(self.comboBox_Energy, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_BeamOn)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8('label_5'))
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.comboBox_PRF = QtWidgets.QComboBox(self.frame_BeamOn)
        self.comboBox_PRF.setEnabled(False)
        self.comboBox_PRF.setObjectName(_fromUtf8('comboBox_PRF'))
        self.comboBox_PRF.addItem(_fromUtf8(''))
        self.comboBox_PRF.addItem(_fromUtf8(''))
        self.comboBox_PRF.addItem(_fromUtf8(''))
        self.comboBox_PRF.addItem(_fromUtf8(''))
        self.comboBox_PRF.addItem(_fromUtf8(''))
        self.comboBox_PRF.addItem(_fromUtf8(''))
        self.gridLayout_2.addWidget(self.comboBox_PRF, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_BeamOn)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8('label'))
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.lineEdit_S_Ion_R = QtWidgets.QLineEdit(self.frame_BeamOn)
        self.lineEdit_S_Ion_R.setReadOnly(True)
        self.lineEdit_S_Ion_R.setObjectName(_fromUtf8('lineEdit_S_Ion_R'))
        self.gridLayout_2.addWidget(self.lineEdit_S_Ion_R, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_BeamOn)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8('label_2'))
        self.gridLayout_2.addWidget(self.label_2, 4, 0, 1, 1)
        self.lineEdit_Flatness_R = QtWidgets.QLineEdit(self.frame_BeamOn)
        self.lineEdit_Flatness_R.setReadOnly(True)
        self.lineEdit_Flatness_R.setObjectName(_fromUtf8('lineEdit_Flatness_R'))
        self.gridLayout_2.addWidget(self.lineEdit_Flatness_R, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_BeamOn)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8('label_3'))
        self.gridLayout_2.addWidget(self.label_3, 5, 0, 1, 1)
        self.lineEdit_S_Ion_T = QtWidgets.QLineEdit(self.frame_BeamOn)
        self.lineEdit_S_Ion_T.setReadOnly(True)
        self.lineEdit_S_Ion_T.setObjectName(_fromUtf8('lineEdit_S_Ion_T'))
        self.gridLayout_2.addWidget(self.lineEdit_S_Ion_T, 5, 1, 1, 1)
        self.lineEdit_Flatness_T = QtWidgets.QLineEdit(self.frame_BeamOn)
        self.lineEdit_Flatness_T.setReadOnly(True)
        self.lineEdit_Flatness_T.setObjectName(_fromUtf8('lineEdit_Flatness_T'))
        self.gridLayout_2.addWidget(self.lineEdit_Flatness_T, 6, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.frame_BeamOn)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName(_fromUtf8('label_45'))
        self.gridLayout_2.addWidget(self.label_45, 7, 0, 1, 1)
        self.lineEdit_dD_Ion = QtWidgets.QLineEdit(self.frame_BeamOn)
        self.lineEdit_dD_Ion.setReadOnly(True)
        self.lineEdit_dD_Ion.setObjectName(_fromUtf8('lineEdit_dD_Ion'))
        self.gridLayout_2.addWidget(self.lineEdit_dD_Ion, 7, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_BeamOn, 0, 0, 1, 1)

        ## parameters readout frame
        self.frame_Parameters = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Parameters.sizePolicy().hasHeightForWidth())
        self.frame_Parameters.setSizePolicy(sizePolicy)
        self.frame_Parameters.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_Parameters.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_Parameters.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Parameters.setObjectName(_fromUtf8('frame_Parameters'))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_Parameters)
        self.verticalLayout.setObjectName(_fromUtf8('verticalLayout'))
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8('gridLayout_3'))
        # self.lineEdit_i_Pos_Rad = QtWidgets.QLineEdit(self.frame_Parameters)
        # self.lineEdit_i_Pos_Rad.setEnabled(False)
        # self.lineEdit_i_Pos_Rad.setReadOnly(True)
        # self.lineEdit_i_Pos_Rad.setObjectName(_fromUtf8('lineEdit_i_Pos_Rad'))
        # self.gridLayout_3.addWidget(self.lineEdit_i_Pos_Rad, 0, 6, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_Parameters)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8('label_18'))
        self.gridLayout_3.addWidget(self.label_18, 1, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_Parameters)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8('label_17'))
        self.gridLayout_3.addWidget(self.label_17, 0, 5, 1, 1)
        # self.lineEdit_Omega = QtWidgets.QLineEdit(self.frame_Parameters)
        # self.lineEdit_Omega.setEnabled(False)
        # self.lineEdit_Omega.setReadOnly(True)
        # self.lineEdit_Omega.setObjectName(_fromUtf8('lineEdit_Omega'))
        # self.gridLayout_3.addWidget(self.lineEdit_Omega, 0, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_Parameters)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8('label_16'))
        self.gridLayout_3.addWidget(self.label_16, 0, 3, 1, 1)
        self.lineEdit_P_Kly_Refl = QtWidgets.QLineEdit(self.frame_Parameters)
        self.lineEdit_P_Kly_Refl.setReadOnly(True)
        self.lineEdit_P_Kly_Refl.setObjectName(_fromUtf8('lineEdit_P_Kly_Refl'))
        self.gridLayout_3.addWidget(self.lineEdit_P_Kly_Refl, 4, 2, 1, 1)
        # self.lineEdit_Tau = QtWidgets.QLineEdit(self.frame_Parameters)
        # self.lineEdit_Tau.setEnabled(False)
        # self.lineEdit_Tau.setReadOnly(True)
        # self.lineEdit_Tau.setObjectName(_fromUtf8('lineEdit_Tau'))
        # self.gridLayout_3.addWidget(self.lineEdit_Tau, 0, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_Parameters)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8('label_9'))
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_Parameters)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8('label_11'))
        self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 1)
        # self.lineEdit_P_AC_Kly = QtWidgets.QLineEdit(self.frame_Parameters)
        # self.lineEdit_P_AC_Kly.setEnabled(False)
        # self.lineEdit_P_AC_Kly.setReadOnly(True)
        # self.lineEdit_P_AC_Kly.setObjectName(_fromUtf8('lineEdit_P_AC_Kly'))
        # self.gridLayout_3.addWidget(self.lineEdit_P_AC_Kly, 1, 2, 1, 1)
        # self.lineEdit_v_Kly = QtWidgets.QLineEdit(self.frame_Parameters)
        # self.lineEdit_v_Kly.setEnabled(False)
        # self.lineEdit_v_Kly.setReadOnly(True)
        # self.lineEdit_v_Kly.setObjectName(_fromUtf8('lineEdit_v_Kly'))
        # self.gridLayout_3.addWidget(self.lineEdit_v_Kly, 2, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_Parameters)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8('label_13'))
        self.gridLayout_3.addWidget(self.label_13, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_Parameters)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8('label_10'))
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_Parameters)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8('label_12'))
        self.gridLayout_3.addWidget(self.label_12, 3, 0, 1, 1)
        self.lineEdit_P_Acc = QtWidgets.QLineEdit(self.frame_Parameters)
        self.lineEdit_P_Acc.setReadOnly(True)
        self.lineEdit_P_Acc.setObjectName(_fromUtf8('lineEdit_P_Acc'))
        self.gridLayout_3.addWidget(self.lineEdit_P_Acc, 3, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_Parameters)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8('label_19'))
        self.gridLayout_3.addWidget(self.label_19, 2, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_Parameters)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8('label_20'))
        self.gridLayout_3.addWidget(self.label_20, 3, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_Parameters)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8('label_21'))
        self.gridLayout_3.addWidget(self.label_21, 4, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_Parameters)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8('label_22'))
        self.gridLayout_3.addWidget(self.label_22, 5, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame_Parameters)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8('label_23'))
        self.gridLayout_3.addWidget(self.label_23, 1, 5, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame_Parameters)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName(_fromUtf8('label_24'))
        self.gridLayout_3.addWidget(self.label_24, 2, 5, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.frame_Parameters)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8('label_25'))
        self.gridLayout_3.addWidget(self.label_25, 3, 5, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame_Parameters)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8('label_26'))
        self.gridLayout_3.addWidget(self.label_26, 4, 5, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_Parameters)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8('label_27'))
        self.gridLayout_3.addWidget(self.label_27, 5, 5, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_Parameters)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName(_fromUtf8('label_28'))
        self.gridLayout_3.addWidget(self.label_28, 7, 5, 1, 1)
        # self.lineEdit_v_Gun = QtWidgets.QLineEdit(self.frame_Parameters)
        # self.lineEdit_v_Gun.setEnabled(False)
        # self.lineEdit_v_Gun.setReadOnly(True)
        # self.lineEdit_v_Gun.setObjectName(_fromUtf8('lineEdit_v_Gun'))
        # self.gridLayout_3.addWidget(self.lineEdit_v_Gun, 1, 4, 1, 1)
        # self.lineEdit_v_Grid = QtWidgets.QLineEdit(self.frame_Parameters)
        # self.lineEdit_v_Grid.setEnabled(False)
        # self.lineEdit_v_Grid.setReadOnly(True)
        # self.lineEdit_v_Grid.setObjectName(_fromUtf8('lineEdit_v_Grid'))
        # self.gridLayout_3.addWidget(self.lineEdit_v_Grid, 2, 4, 1, 1)
        # self.lineEdit_i_Coil_BMag = QtWidgets.QLineEdit(self.frame_Parameters)
        # self.lineEdit_i_Coil_BMag.setEnabled(False)
        # self.lineEdit_i_Coil_BMag.setReadOnly(True)
        # self.lineEdit_i_Coil_BMag.setObjectName(_fromUtf8('lineEdit_i_Coil_BMag'))
        # self.gridLayout_3.addWidget(self.lineEdit_i_Coil_BMag, 3, 4, 1, 1)
        self.lineEdit_i_Acc = QtWidgets.QLineEdit(self.frame_Parameters)
        self.lineEdit_i_Acc.setEnabled(True)
        self.lineEdit_i_Acc.setFrame(True)
        self.lineEdit_i_Acc.setReadOnly(True)
        self.lineEdit_i_Acc.setObjectName(_fromUtf8('lineEdit_i_Acc'))
        self.gridLayout_3.addWidget(self.lineEdit_i_Acc, 4, 4, 1, 1)
        self.lineEdit_i_Tar = QtWidgets.QLineEdit(self.frame_Parameters)
        self.lineEdit_i_Tar.setReadOnly(True)
        self.lineEdit_i_Tar.setObjectName(_fromUtf8('lineEdit_i_Tar'))
        self.gridLayout_3.addWidget(self.lineEdit_i_Tar, 5, 4, 1, 1)
        # self.lineEdit_i_Pos_Trans = QtWidgets.QLineEdit(self.frame_Parameters)
        # self.lineEdit_i_Pos_Trans.setEnabled(False)
        # self.lineEdit_i_Pos_Trans.setReadOnly(True)
        # self.lineEdit_i_Pos_Trans.setObjectName(_fromUtf8('lineEdit_i_Pos_Trans'))
        # self.gridLayout_3.addWidget(self.lineEdit_i_Pos_Trans, 1, 6, 1, 1)
        # self.lineEdit_i_Ang_Rad = QtWidgets.QLineEdit(self.frame_Parameters)
        # self.lineEdit_i_Ang_Rad.setEnabled(False)
        # self.lineEdit_i_Ang_Rad.setReadOnly(True)
        # self.lineEdit_i_Ang_Rad.setObjectName(_fromUtf8('lineEdit_i_Ang_Rad'))
        # self.gridLayout_3.addWidget(self.lineEdit_i_Ang_Rad, 2, 6, 1, 1)
        # self.lineEdit_i_Ang_Trans = QtWidgets.QLineEdit(self.frame_Parameters)
        # self.lineEdit_i_Ang_Trans.setEnabled(False)
        # self.lineEdit_i_Ang_Trans.setReadOnly(True)
        # self.lineEdit_i_Ang_Trans.setObjectName(_fromUtf8('lineEdit_i_Ang_Trans'))
        # self.gridLayout_3.addWidget(self.lineEdit_i_Ang_Trans, 3, 6, 1, 1)
        # self.lineEdit_Rad_Jaw = QtWidgets.QLineEdit(self.frame_Parameters)
        # self.lineEdit_Rad_Jaw.setEnabled(False)
        # self.lineEdit_Rad_Jaw.setReadOnly(True)
        # self.lineEdit_Rad_Jaw.setObjectName(_fromUtf8('lineEdit_Rad_Jaw'))
        # self.gridLayout_3.addWidget(self.lineEdit_Rad_Jaw, 4, 6, 1, 1)
        # self.lineEdit_Trans_Jaw = QtWidgets.QLineEdit(self.frame_Parameters)
        # self.lineEdit_Trans_Jaw.setEnabled(False)
        # self.lineEdit_Trans_Jaw.setReadOnly(True)
        # self.lineEdit_Trans_Jaw.setObjectName(_fromUtf8('lineEdit_Trans_Jaw'))
        # self.gridLayout_3.addWidget(self.lineEdit_Trans_Jaw, 5, 6, 1, 1)
        # self.lineEdit_d_Tank = QtWidgets.QLineEdit(self.frame_Parameters)
        # self.lineEdit_d_Tank.setEnabled(False)
        # self.lineEdit_d_Tank.setReadOnly(True)
        # self.lineEdit_d_Tank.setObjectName(_fromUtf8('lineEdit_d_Tank'))
        # self.gridLayout_3.addWidget(self.lineEdit_d_Tank, 7, 6, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout.addWidget(self.frame_Parameters, 1, 0, 1, 2) # was 0, 1, 1, 2

        ## photo frame
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(260, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName(_fromUtf8('frame_5'))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName(_fromUtf8('horizontalLayout_2'))
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setText(_fromUtf8('tst'))
        # changed image and scaled it properly
        self.label_8.setPixmap(QtGui.QPixmap(_fromUtf8('resources/images/Linac_new.jpg')).scaled(self.label_8.size()*2, 2, QtCore.Qt.SmoothTransformation))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName(_fromUtf8('label_8'))
        # added tooltip
        self.label_8.setToolTip('https://commons.wikimedia.org/wiki/File:Linear_Accelerator_-_Elekta_Compact_model.jpg')
        self.horizontalLayout_2.addWidget(self.label_8)
        self.gridLayout.addWidget(self.frame_5, 1, 2, 2, 1)

        ## sliders input frame
        # startup values are either hardcoded (self.horizontalScrollBar_Tau.setProperty('value', 3)) or missing altogether
        
        self.frame_Sliders = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Sliders.sizePolicy().hasHeightForWidth())
        self.frame_Sliders.setSizePolicy(sizePolicy)
        self.frame_Sliders.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.frame_Sliders.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Sliders.setObjectName(_fromUtf8('frame_Sliders'))
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_Sliders)
        self.gridLayout_9.setObjectName(_fromUtf8('gridLayout_9'))
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8('gridLayout_4'))
        self.label_38 = QtWidgets.QLabel(self.frame_Sliders)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName(_fromUtf8('label_38'))
        self.gridLayout_4.addWidget(self.label_38, 5, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.frame_Sliders)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName(_fromUtf8('label_42'))
        self.gridLayout_4.addWidget(self.label_42, 7, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.frame_Sliders)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName(_fromUtf8('label_43'))
        self.gridLayout_4.addWidget(self.label_43, 7, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.frame_Sliders)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName(_fromUtf8('label_36'))
        self.gridLayout_4.addWidget(self.label_36, 2, 3, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.frame_Sliders)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName(_fromUtf8('label_34'))
        self.gridLayout_4.addWidget(self.label_34, 2, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.frame_Sliders)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName(_fromUtf8('label_39'))
        self.gridLayout_4.addWidget(self.label_39, 5, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.frame_Sliders)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName(_fromUtf8('label_37'))
        self.gridLayout_4.addWidget(self.label_37, 5, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.frame_Sliders)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName(_fromUtf8('label_32'))
        self.gridLayout_4.addWidget(self.label_32, 0, 3, 1, 1)
        self.horizontalScrollBar_v_Kly = QtWidgets.QDoubleSpinBox(self.frame_Sliders) # was QScrollBar
        self.horizontalScrollBar_v_Kly.setEnabled(False)
        self.horizontalScrollBar_v_Kly.setMaximum(150)
        #self.horizontalScrollBar_v_Kly.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_v_Kly.setObjectName(_fromUtf8('horizontalScrollBar_v_Kly'))
        self.gridLayout_4.addWidget(self.horizontalScrollBar_v_Kly, 6, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.frame_Sliders)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName(_fromUtf8('label_35'))
        self.gridLayout_4.addWidget(self.label_35, 2, 2, 1, 1)
        self.horizontalScrollBar_Omega = QtWidgets.QDoubleSpinBox(self.frame_Sliders)  #was QScrollBar
        self.horizontalScrollBar_Omega.setEnabled(False)
        self.horizontalScrollBar_Omega.setMinimum(2855.50)   # previously 285550
        self.horizontalScrollBar_Omega.setMaximum(2856.50)   # previously 285650
        self.horizontalScrollBar_Omega.setSingleStep(0.05)   # previously 5
        self.horizontalScrollBar_Omega.setProperty('value', 2856.00)   # previously 285600
        #self.horizontalScrollBar_Omega.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_Omega.setObjectName(_fromUtf8('horizontalScrollBar_Omega'))
        self.gridLayout_4.addWidget(self.horizontalScrollBar_Omega, 1, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.frame_Sliders)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName(_fromUtf8('label_31'))
        self.gridLayout_4.addWidget(self.label_31, 0, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.frame_Sliders)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName(_fromUtf8('label_33'))
        self.gridLayout_4.addWidget(self.label_33, 2, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame_Sliders)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName(_fromUtf8('label_29'))
        self.gridLayout_4.addWidget(self.label_29, 0, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_Sliders)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName(_fromUtf8('label_30'))
        self.gridLayout_4.addWidget(self.label_30, 0, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.frame_Sliders)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName(_fromUtf8('label_40'))
        self.gridLayout_4.addWidget(self.label_40, 5, 3, 1, 1)
        self.horizontalScrollBar_Tau = QtWidgets.QDoubleSpinBox(self.frame_Sliders) # was QScrollBar
        self.horizontalScrollBar_Tau.setEnabled(False)
        self.horizontalScrollBar_Tau.setMinimum(2)  # was 20
        self.horizontalScrollBar_Tau.setMaximum(4)    # was 40
        # change step size
        self.horizontalScrollBar_Tau.setSingleStep(0.1)
        self.horizontalScrollBar_Tau.setProperty('value', 3)    # was 30
        #self.horizontalScrollBar_Tau.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_Tau.setObjectName(_fromUtf8('horizontalScrollBar_Tau'))
        self.gridLayout_4.addWidget(self.horizontalScrollBar_Tau, 1, 1, 1, 1)
        self.horizontalScrollBar_i_Pos_Rad = QtWidgets.QDoubleSpinBox(self.frame_Sliders) # was QScrollBar
        self.horizontalScrollBar_i_Pos_Rad.setEnabled(False)
        self.horizontalScrollBar_i_Pos_Rad.setMinimum(-200)
        self.horizontalScrollBar_i_Pos_Rad.setMaximum(200)
        #self.horizontalScrollBar_i_Pos_Rad.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_i_Pos_Rad.setObjectName(_fromUtf8('horizontalScrollBar_i_Pos_Rad'))
        self.gridLayout_4.addWidget(self.horizontalScrollBar_i_Pos_Rad, 1, 2, 1, 1)
        self.horizontalScrollBar_v_Grid = QtWidgets.QDoubleSpinBox(self.frame_Sliders) # was QScrollBar
        self.horizontalScrollBar_v_Grid.setEnabled(False)
        self.horizontalScrollBar_v_Grid.setMinimum(-200)
        self.horizontalScrollBar_v_Grid.setMaximum(0)
        #self.horizontalScrollBar_v_Grid.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_v_Grid.setObjectName(_fromUtf8('horizontalScrollBar_v_Grid'))
        self.gridLayout_4.addWidget(self.horizontalScrollBar_v_Grid, 6, 1, 1, 1)
        self.horizontalScrollBar_Trans_Jaw = QtWidgets.QDoubleSpinBox(self.frame_Sliders) # was QScrollBar
        self.horizontalScrollBar_Trans_Jaw.setEnabled(False)
        self.horizontalScrollBar_Trans_Jaw.setMinimum(3)
        self.horizontalScrollBar_Trans_Jaw.setMaximum(20)
        self.horizontalScrollBar_Trans_Jaw.setProperty('value', 15)
        #self.horizontalScrollBar_Trans_Jaw.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_Trans_Jaw.setObjectName(_fromUtf8('horizontalScrollBar_Trans_Jaw'))
        self.gridLayout_4.addWidget(self.horizontalScrollBar_Trans_Jaw, 3, 3, 1, 1)
        self.horizontalScrollBar_i_Pos_Trans = QtWidgets.QDoubleSpinBox(self.frame_Sliders) # was QScrollBar
        self.horizontalScrollBar_i_Pos_Trans.setEnabled(False)
        self.horizontalScrollBar_i_Pos_Trans.setMinimum(-200)
        self.horizontalScrollBar_i_Pos_Trans.setMaximum(200)
        #self.horizontalScrollBar_i_Pos_Trans.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_i_Pos_Trans.setObjectName(_fromUtf8('horizontalScrollBar_i_Pos_Trans'))
        self.gridLayout_4.addWidget(self.horizontalScrollBar_i_Pos_Trans, 3, 2, 1, 1)
        self.horizontalScrollBar_Rad_Jaw = QtWidgets.QDoubleSpinBox(self.frame_Sliders) # was QScrollBar
        self.horizontalScrollBar_Rad_Jaw.setEnabled(False)
        self.horizontalScrollBar_Rad_Jaw.setMinimum(3)
        self.horizontalScrollBar_Rad_Jaw.setMaximum(20)
        self.horizontalScrollBar_Rad_Jaw.setProperty('value', 15)
        #self.horizontalScrollBar_Rad_Jaw.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_Rad_Jaw.setObjectName(_fromUtf8('horizontalScrollBar_Rad_Jaw'))
        self.gridLayout_4.addWidget(self.horizontalScrollBar_Rad_Jaw, 1, 3, 1, 1)
        self.horizontalScrollBar_P_AC_Kly = QtWidgets.QDoubleSpinBox(self.frame_Sliders) # was QScrollBar
        self.horizontalScrollBar_P_AC_Kly.setEnabled(False)
        self.horizontalScrollBar_P_AC_Kly.setMaximum(200)
        #self.horizontalScrollBar_P_AC_Kly.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_P_AC_Kly.setObjectName(_fromUtf8('horizontalScrollBar_P_AC_Kly'))
        self.gridLayout_4.addWidget(self.horizontalScrollBar_P_AC_Kly, 3, 0, 1, 1)
        self.horizontalScrollBar_v_Gun = QtWidgets.QDoubleSpinBox(self.frame_Sliders) # was QScrollBar
        self.horizontalScrollBar_v_Gun.setEnabled(False)
        self.horizontalScrollBar_v_Gun.setMaximum(20)
        #self.horizontalScrollBar_v_Gun.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_v_Gun.setObjectName(_fromUtf8('horizontalScrollBar_v_Gun'))
        self.gridLayout_4.addWidget(self.horizontalScrollBar_v_Gun, 3, 1, 1, 1)
        self.horizontalScrollBar_i_Ang_Rad = QtWidgets.QDoubleSpinBox(self.frame_Sliders) # was QScrollBar
        self.horizontalScrollBar_i_Ang_Rad.setEnabled(False)
        self.horizontalScrollBar_i_Ang_Rad.setMinimum(-200)
        self.horizontalScrollBar_i_Ang_Rad.setMaximum(200)
        #self.horizontalScrollBar_i_Ang_Rad.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_i_Ang_Rad.setObjectName(_fromUtf8('horizontalScrollBar_i_Ang_Rad'))
        self.gridLayout_4.addWidget(self.horizontalScrollBar_i_Ang_Rad, 6, 2, 1, 1)
        self.horizontalScrollBar_d_Tank = QtWidgets.QDoubleSpinBox(self.frame_Sliders) # was QScrollBar
        self.horizontalScrollBar_d_Tank.setEnabled(False)
        self.horizontalScrollBar_d_Tank.setAutoFillBackground(False)
        self.horizontalScrollBar_d_Tank.setMaximum(30)
        #self.horizontalScrollBar_d_Tank.setOrientation(QtCore.Qt.Horizontal)
        #self.horizontalScrollBar_d_Tank.setInvertedAppearance(False)
        #self.horizontalScrollBar_d_Tank.setInvertedControls(False)
        self.horizontalScrollBar_d_Tank.setObjectName(_fromUtf8('horizontalScrollBar_d_Tank'))
        self.gridLayout_4.addWidget(self.horizontalScrollBar_d_Tank, 6, 3, 1, 1)
        self.horizontalScrollBar_i_Coil_BMag = QtWidgets.QDoubleSpinBox(self.frame_Sliders) # was QScrollBar
        self.horizontalScrollBar_i_Coil_BMag.setEnabled(False)
        self.horizontalScrollBar_i_Coil_BMag.setMaximum(200)
        #self.horizontalScrollBar_i_Coil_BMag.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_i_Coil_BMag.setObjectName(_fromUtf8('horizontalScrollBar_i_Coil_BMag'))
        self.gridLayout_4.addWidget(self.horizontalScrollBar_i_Coil_BMag, 8, 1, 1, 1)
        self.horizontalScrollBar_i_Ang_Trans = QtWidgets.QDoubleSpinBox(self.frame_Sliders) # was QScrollBar
        self.horizontalScrollBar_i_Ang_Trans.setEnabled(False)
        self.horizontalScrollBar_i_Ang_Trans.setMinimum(-200)
        self.horizontalScrollBar_i_Ang_Trans.setMaximum(200)
        #self.horizontalScrollBar_i_Ang_Trans.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_i_Ang_Trans.setObjectName(_fromUtf8('horizontalScrollBar_i_Ang_Trans'))
        self.gridLayout_4.addWidget(self.horizontalScrollBar_i_Ang_Trans, 8, 2, 1, 1)
# "calculate" pushbutton
        self.pushButton_UpdateLinacModel = QtWidgets.QPushButton(self.frame_Sliders)
        self.pushButton_UpdateLinacModel.setObjectName(_fromUtf8('pushButton_UpdateLinacModel'))
        #added tooltip and bold font
        self.pushButton_UpdateLinacModel.setToolTip('Ctrl-C')
        self.pushButton_UpdateLinacModel.setStyleSheet("font-weight: bold")
        self.gridLayout_4.addWidget(self.pushButton_UpdateLinacModel, 8, 3, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_Sliders, 0, 1, 1, 2) # was 2, 0, 1, 2

        ## window pushbuttons frame
        self.frame_PushButtons = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_PushButtons.sizePolicy().hasHeightForWidth())
        self.frame_PushButtons.setSizePolicy(sizePolicy)
        self.frame_PushButtons.setMaximumSize(QtCore.QSize(2000, 2000))
        self.frame_PushButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_PushButtons.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_PushButtons.setObjectName(_fromUtf8('frame_PushButtons'))
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_PushButtons)
        self.gridLayout_8.setObjectName(_fromUtf8('gridLayout_8'))
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8('horizontalLayout'))
# "klystron" pushbutton
        self.pushButton_Klystron = QtWidgets.QPushButton(self.frame_PushButtons)
        self.pushButton_Klystron.setMinimumSize(QtCore.QSize(80, 68))
        self.pushButton_Klystron.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Klystron.setFont(font)
        self.pushButton_Klystron.setObjectName(_fromUtf8('pushButton_Klystron'))
        #new tooltip
        self.pushButton_Klystron.setToolTip('Open Klystron window (Ctrl-K)')
        self.horizontalLayout.addWidget(self.pushButton_Klystron)
        self.pushButton_Accelerator = QtWidgets.QPushButton(self.frame_PushButtons)
        self.pushButton_Accelerator.setMinimumSize(QtCore.QSize(0, 70))
        self.pushButton_Accelerator.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Accelerator.setFont(font)
        self.pushButton_Accelerator.setObjectName(_fromUtf8('pushButton_Accelerator'))
        self.pushButton_Accelerator.setToolTip('Open Accelerator window (Ctrl-A)')
        self.horizontalLayout.addWidget(self.pushButton_Accelerator)
        self.pushButton_TreatmentHead = QtWidgets.QPushButton(self.frame_PushButtons)
        self.pushButton_TreatmentHead.setMinimumSize(QtCore.QSize(0, 70))
        self.pushButton_TreatmentHead.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_TreatmentHead.setFont(font)
        self.pushButton_TreatmentHead.setObjectName(_fromUtf8('pushButton_TreatmentHead'))
        self.pushButton_TreatmentHead.setToolTip('Open Treatment Head window (Ctrl-T)')
        self.horizontalLayout.addWidget(self.pushButton_TreatmentHead)
        self.gridLayout_8.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_PushButtons, 2, 0, 1, 2) # was 1, 0, 1, 2

        ## menu bar
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8('menubar'))
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8('menuHelp'))
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8('menuFile'))
        MainWindow.setMenuBar(self.menubar)

        ## status bar
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8('statusbar'))
        MainWindow.setStatusBar(self.statusbar)

        ## actions
        self.actionAbout_LinacSimPy = QtWidgets.QAction(MainWindow)
        self.actionAbout_LinacSimPy.setObjectName(_fromUtf8('actionAbout_LinacSimPy'))
        self.actionLicense = QtWidgets.QAction(MainWindow)
        self.actionLicense.setObjectName(_fromUtf8('actionLicense'))
        self.actionTutorial = QtWidgets.QAction(MainWindow)
        self.actionTutorial.setObjectName(_fromUtf8('actionTutorial'))
        self.actionTheory = QtWidgets.QAction(MainWindow)
        self.actionTheory.setObjectName(_fromUtf8('actionTheory'))
        self.actionLoad_ini = QtWidgets.QAction(MainWindow)
        self.actionLoad_ini.setObjectName(_fromUtf8('actionLoad_ini'))
        self.actionSave_ini = QtWidgets.QAction(MainWindow)
        self.actionSave_ini.setObjectName(_fromUtf8('actionSave_ini'))
        self.actionConvert_log_file = QtWidgets.QAction(MainWindow)
        self.actionConvert_log_file.setObjectName(_fromUtf8('actionConvert_log_file'))
        self.actionCreate_config_file = QtWidgets.QAction(MainWindow)
        self.actionCreate_config_file.setObjectName(_fromUtf8('actionCreate_config_file'))
        self.actionLoad_Exercise = QtWidgets.QAction(MainWindow)
        self.actionLoad_Exercise.setObjectName(_fromUtf8('actionLoad_Exercise'))
        self.actionValidate_Exercise = QtWidgets.QAction(MainWindow)
        self.actionValidate_Exercise.setObjectName(_fromUtf8('actionValidate_Exercise'))
        self.actionSave_Exercise = QtWidgets.QAction(MainWindow)
        self.actionSave_Exercise.setObjectName(_fromUtf8('actionSave_Exercise'))
        #added exit in menu
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8('actionExit'))
        self.menuHelp.addAction(self.actionAbout_LinacSimPy)
        self.menuHelp.addSeparator() # added
        self.menuHelp.addAction(self.actionLicense)
        self.menuHelp.addAction(self.actionTutorial)
        self.menuHelp.addAction(self.actionTheory)
        self.menuFile.addAction(self.actionLoad_ini)
        self.menuFile.addAction(self.actionSave_ini)
        self.menuFile.addAction(self.actionLoad_Exercise)
        self.menuFile.addAction(self.actionValidate_Exercise)
        self.menuFile.addAction(self.actionSave_Exercise)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionConvert_log_file)
        self.menuFile.addAction(self.actionCreate_config_file)
        #added
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

# looks like function below is automatically generated by QT designer to support multiple languages
# https://stackoverflow.com/questions/66361580/what-does-retranslateui-do-in-pyqt
# commented out initialization values of edit boxes
    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate('MainWindow', 'LinacSimPy', None))
        self.label_4.setText(_translate('MainWindow', 'Trans F [%]', None))
        self.label_7.setText(_translate('MainWindow', 'Beam On/Off', None))
        self.pushButton_BeamOn.setText(_translate('MainWindow', 'On/Off', None))
        self.label_6.setText(_translate('MainWindow', 'Energy', None))
        self.comboBox_Energy.setItemText(0, _translate('MainWindow', 'Idle', None))
        self.comboBox_Energy.setItemText(1, _translate('MainWindow', '6MV', None))
        self.comboBox_Energy.setItemText(2, _translate('MainWindow', '15MV', None))
        self.label_5.setText(_translate('MainWindow', 'PRF [Hz]', None))
        self.comboBox_PRF.setItemText(0, _translate('MainWindow', '60Hz', None))
        self.comboBox_PRF.setItemText(1, _translate('MainWindow', '120Hz', None))
        self.comboBox_PRF.setItemText(2, _translate('MainWindow', '180Hz', None))
        self.comboBox_PRF.setItemText(3, _translate('MainWindow', '240Hz', None))
        self.comboBox_PRF.setItemText(4, _translate('MainWindow', '300Hz', None))
        self.comboBox_PRF.setItemText(5, _translate('MainWindow', '360Hz', None))
        self.label.setText(_translate('MainWindow', 'Rad S [%]', None))
        # self.lineEdit_S_Ion_R.setText(_translate('MainWindow', '0', None))
        self.label_2.setText(_translate('MainWindow', 'Rad F [%]', None))
        # self.lineEdit_Flatness_R.setText(_translate('MainWindow', '0', None))
        self.label_3.setText(_translate('MainWindow', 'Trans S [%]', None))
        # self.lineEdit_S_Ion_T.setText(_translate('MainWindow', '0', None))
        # self.lineEdit_Flatness_T.setText(_translate('MainWindow', '0', None))
        self.label_45.setText(_translate('MainWindow', 'Dose [cGy/Min]', None))
        # self.lineEdit_dD_Ion.setText(_translate('MainWindow', '0', None))
        # self.lineEdit_i_Pos_Rad.setText(_translate('MainWindow', '0', None))
        self.label_18.setText(_translate('MainWindow', 'Gun V [kV]', None))
        self.label_17.setText(_translate('MainWindow', 'Pos R [mA]', None))
        # self.lineEdit_Omega.setText(_translate('MainWindow', '2856.00', None))
        self.label_16.setText(_translate('MainWindow', 'Width [us]', None))
        # self.lineEdit_P_Kly_Refl.setText(_translate('MainWindow', '0', None))
        # self.lineEdit_Tau.setText(_translate('MainWindow', '3', None))
        self.label_9.setText(_translate('MainWindow', 'RF Freq [MHz]', None))
        self.label_11.setText(_translate('MainWindow', 'Kly V [kV]', None))
        # self.lineEdit_P_AC_Kly.setText(_translate('MainWindow', '0', None))
        # self.lineEdit_v_Kly.setText(_translate('MainWindow', '0', None))
        self.label_13.setText(_translate('MainWindow', 'P Refl [MW]', None))
        self.label_10.setText(_translate('MainWindow', 'RF in [W]', None))
        self.label_12.setText(_translate('MainWindow', 'RF Out [MW]', None))
        # self.lineEdit_P_Acc.setText(_translate('MainWindow', '0', None))
        self.label_19.setText(_translate('MainWindow', 'Grid V [V]', None))
        self.label_20.setText(_translate('MainWindow', 'BMag I [A]', None))
        self.label_21.setText(_translate('MainWindow', 'Gun I [mA]', None))
        self.label_22.setText(_translate('MainWindow', 'Tar I [mA]', None))
        self.label_23.setText(_translate('MainWindow', 'Pos T [mA]', None))
        self.label_24.setText(_translate('MainWindow', 'Ang R [mA]', None))
        self.label_25.setText(_translate('MainWindow', 'Ang T [mA]', None))
        self.label_26.setText(_translate('MainWindow', 'Jaw R [cm]', None))
        self.label_27.setText(_translate('MainWindow', 'Jaw T [cm]', None))
        self.label_28.setText(_translate('MainWindow', 'Depth [cm]', None))
        # self.lineEdit_v_Gun.setText(_translate('MainWindow', '0', None))
        # self.lineEdit_v_Grid.setText(_translate('MainWindow', '0', None))
        # self.lineEdit_i_Coil_BMag.setText(_translate('MainWindow', '0', None))
        # self.lineEdit_i_Acc.setText(_translate('MainWindow', '0', None))
        # self.lineEdit_i_Tar.setText(_translate('MainWindow', '0', None))
        # self.lineEdit_i_Pos_Trans.setText(_translate('MainWindow', '0', None))
        # self.lineEdit_i_Ang_Rad.setText(_translate('MainWindow', '0', None))
        # self.lineEdit_i_Ang_Trans.setText(_translate('MainWindow', '0', None))
        # self.lineEdit_Rad_Jaw.setText(_translate('MainWindow', '15', None))
        # self.lineEdit_Trans_Jaw.setText(_translate('MainWindow', '15', None))
        # self.lineEdit_d_Tank.setText(_translate('MainWindow', '0', None))
        self.label_38.setText(_translate('MainWindow', 'Grid V [V]', None))
        self.label_42.setText(_translate('MainWindow', 'BMag I [A]', None))
        self.label_43.setText(_translate('MainWindow', 'Ang T [mA]', None))
        self.label_36.setText(_translate('MainWindow', 'Jaw T [cm]', None))
        self.label_34.setText(_translate('MainWindow', 'Gun V [kV]', None))
        self.label_39.setText(_translate('MainWindow', 'Ang R [mA]', None))
        self.label_37.setText(_translate('MainWindow', 'Kly V [kV]', None))
        self.label_32.setText(_translate('MainWindow', 'Jaw R [cm]', None))
        self.label_35.setText(_translate('MainWindow', 'Pos T [mA]', None))
        self.label_31.setText(_translate('MainWindow', 'Pos R [mA]', None))
        self.label_33.setText(_translate('MainWindow', 'RF In [W]', None))
        self.label_29.setText(_translate('MainWindow', 'RF Freq [MHz]', None))
        self.label_30.setText(_translate('MainWindow', 'Width [us]', None))
        self.label_40.setText(_translate('MainWindow', 'Depth [cm]', None))
        self.pushButton_UpdateLinacModel.setText(_translate('MainWindow', 'Calculate', None))
        self.pushButton_Klystron.setText(_translate('MainWindow', 'Klystron', None))
        self.pushButton_Accelerator.setText(_translate('MainWindow', 'Accelerator', None))
        self.pushButton_TreatmentHead.setText(_translate('MainWindow', 'Treatment Head', None))
        self.menuHelp.setTitle(_translate('MainWindow', 'Help', None))
        self.menuFile.setTitle(_translate('MainWindow', 'File', None))
        self.actionAbout_LinacSimPy.setText(_translate('MainWindow', 'About LinacSimPy', None))
        self.actionLicense.setText(_translate('MainWindow', 'License', None))
        self.actionTutorial.setText(_translate('MainWindow', 'Tutorial', None))
        self.actionTheory.setText(_translate('MainWindow', 'Theory', None))
        self.actionLoad_ini.setText(_translate('MainWindow', 'Load Linac Status (.json) ...', None))
        self.actionSave_ini.setText(_translate('MainWindow', 'Save Linac Status (.json) ...', None))
        self.actionConvert_log_file.setText(_translate('MainWindow', 'Convert Exercise Output ...', None))
        self.actionCreate_config_file.setText(_translate('MainWindow', 'Create Exercise File ...', None))
        self.actionLoad_Exercise.setText(_translate('MainWindow', 'Load Exercise (binary) ...', None))
        self.actionValidate_Exercise.setText(_translate('MainWindow', 'Validate Exercise ?? ...', None))
        self.actionSave_Exercise.setText(_translate('MainWindow', 'Save Exercise Output (binary) ...', None))
        self.actionExit.setText(_translate('MainWindow', 'Exit LinacSimPy (Ctrl-Q) ...', None)) # added menu item
        return
