# LinacSimPy is an interactive model of a medical linear accelerator (LINAC)

# © 2025 Alberta Health Services, Medical Physics

# This file is part of LinacSimPy.
# LinacSimPy is free software: you can redistribute it and/or modify it under the terms 
# of the GNU General Public License as published by the Free Software Foundation, either 
# version 3 of the License, or (at your option) any later version.
# LinacSimPy is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with LinacSimPy. 
# If not, see <https://www.gnu.org/licenses/>.

# This material is intended for general information only and is provided on an "as is", "where is" 
# basis. Although reasonable efforts were made to confirm the accuracy of the information, 
# Alberta Health Services does not make any representation or warranty, express, implied or 
# statutory, as to the accuracy, reliability, completeness, applicability or fitness for a particular 
# purpose of such information. This material is not a substitute for the advice of a qualified health 
# professional. Alberta Health Services expressly disclaims all liability for the use of these 
# materials, and for any claims, actions, demands or suits arising from such use.



from PyQt5 import QtCore, QtGui, QtWidgets
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:

    def _fromUtf8(s):
        return s


try:
    _encoding = QtGui.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)


except AttributeError:

    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)


class Ui_Form(object):

    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8('Form'))
        # commented out statements that lock window size
        # Form.resize(802, 650)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        # Form.setSizePolicy(sizePolicy)
        # Form.setMinimumSize(QtCore.QSize(800, 650))
        # Form.setMaximumSize(QtCore.QSize(1000, 650))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Form.setPalette(palette)
        # for some reason gridLayout and gridLayout_6 are nested grids holding the 4 main frames (see line 662)
        #self.gridLayout_6 = QtWidgets.QGridLayout(Form)
        #self.gridLayout_6.setObjectName(_fromUtf8('gridLayout_6'))
        #self.gridLayout = QtWidgets.QGridLayout()
        #self.gridLayout.setObjectName(_fromUtf8('gridLayout'))
        
        # split original grid into nested horizontal and vertical layouts
        
        self.verticalStack = QtWidgets.QVBoxLayout(Form)
        self.topRow = QtWidgets.QHBoxLayout()
        self.topRow.setObjectName(_fromUtf8('topRow'))
        self.bottomRow = QtWidgets.QHBoxLayout()
        self.bottomRow.setObjectName(_fromUtf8('bottomRow'))  
                                     
        # top left frame
        edit_box_width = 60     #hard coded width to make text fit
        self.frame_TL = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)  # was 0
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_TL.sizePolicy().hasHeightForWidth())
        self.frame_TL.setSizePolicy(sizePolicy)
        self.frame_TL.setMinimumSize(QtCore.QSize(0, 0))    # was 390, 270; setting to 600 does make it wider
        self.frame_TL.setMaximumSize(QtCore.QSize(600, 320))    #450 was 390
        self.frame_TL.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TL.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_TL.setObjectName(_fromUtf8('frame_TL'))
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_TL)
        self.gridLayout_7.setContentsMargins(0,0,0,0)
        self.gridLayout_7.setObjectName(_fromUtf8('gridLayout_7'))
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8('gridLayout_5'))
        # measurable parameters and radio buttons frame (frame_5)
        self.frame_5 = QtWidgets.QFrame(self.frame_TL)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8('frame_5'))
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_11.setContentsMargins(12,12,12,12)
        self.gridLayout_11.setObjectName(_fromUtf8('gridLayout_11'))
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8('gridLayout_3'))
        # channel B buttons
        self.groupBox_ChB = QtWidgets.QGroupBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_ChB.sizePolicy().hasHeightForWidth())
        self.groupBox_ChB.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_ChB.setFont(font)
        self.groupBox_ChB.setObjectName(_fromUtf8('groupBox_ChB'))
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_ChB)
        self.gridLayout_17.setObjectName(_fromUtf8('gridLayout_17'))
        self.radioButton_ChB_1 = QtWidgets.QRadioButton(self.groupBox_ChB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_ChB_1.sizePolicy().hasHeightForWidth())
        self.radioButton_ChB_1.setSizePolicy(sizePolicy)
        self.radioButton_ChB_1.setText(_fromUtf8(''))
        self.radioButton_ChB_1.setChecked(True)
        self.radioButton_ChB_1.setObjectName(_fromUtf8('radioButton_ChB_1'))
        self.gridLayout_17.addWidget(self.radioButton_ChB_1, 0, 0, 1, 1)
        self.radioButton_ChB_2 = QtWidgets.QRadioButton(self.groupBox_ChB)
        self.radioButton_ChB_2.setText(_fromUtf8(''))
        self.radioButton_ChB_2.setObjectName(_fromUtf8('radioButton_ChB_2'))
        self.gridLayout_17.addWidget(self.radioButton_ChB_2, 1, 0, 1, 1)
        self.radioButton_ChB_3 = QtWidgets.QRadioButton(self.groupBox_ChB)
        self.radioButton_ChB_3.setText(_fromUtf8(''))
        self.radioButton_ChB_3.setObjectName(_fromUtf8('radioButton_ChB_3'))
        self.gridLayout_17.addWidget(self.radioButton_ChB_3, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_ChB, 0, 2, 1, 1)
        # channel A buttons
        self.groupBox_ChA = QtWidgets.QGroupBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_ChA.sizePolicy().hasHeightForWidth())
        self.groupBox_ChA.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_ChA.setFont(font)
        self.groupBox_ChA.setObjectName(_fromUtf8('groupBox_ChA'))
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_ChA)
        self.gridLayout_15.setObjectName(_fromUtf8('gridLayout_15'))
        self.radioButton_ChA_1 = QtWidgets.QRadioButton(self.groupBox_ChA)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_ChA_1.sizePolicy().hasHeightForWidth())
        self.radioButton_ChA_1.setSizePolicy(sizePolicy)
        self.radioButton_ChA_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_ChA_1.setText(_fromUtf8(''))
        self.radioButton_ChA_1.setChecked(True)
        self.radioButton_ChA_1.setObjectName(_fromUtf8('radioButton_ChA_1'))
        self.gridLayout_15.addWidget(self.radioButton_ChA_1, 0, 0, 1, 1)
        self.radioButton_ChA_2 = QtWidgets.QRadioButton(self.groupBox_ChA)
        self.radioButton_ChA_2.setText(_fromUtf8(''))
        self.radioButton_ChA_2.setObjectName(_fromUtf8('radioButton_ChA_2'))
        self.gridLayout_15.addWidget(self.radioButton_ChA_2, 1, 0, 1, 1)
        self.radioButton_ChA_3 = QtWidgets.QRadioButton(self.groupBox_ChA)
        self.radioButton_ChA_3.setText(_fromUtf8(''))
        self.radioButton_ChA_3.setObjectName(_fromUtf8('radioButton_ChA_3'))
        self.gridLayout_15.addWidget(self.radioButton_ChA_3, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_ChA, 0, 1, 1, 1)
        
        # measurable parameters frame (frame_7)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setLineWidth(0)
        self.frame_7.setObjectName(_fromUtf8('frame_7'))
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_13.setContentsMargins(0,0,0,0)
        self.gridLayout_13.setObjectName(_fromUtf8('gridLayout_13'))
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8('gridLayout_4'))
        
        # RF power text
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8('label_8'))
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        
        # RF power number
        self.lineEdit_P_Acc = QtWidgets.QLineEdit(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_P_Acc.sizePolicy().hasHeightForWidth())
        self.lineEdit_P_Acc.setSizePolicy(sizePolicy)
        self.lineEdit_P_Acc.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_P_Acc.setFixedSize(edit_box_width, 20)    #added to make narrower
        self.lineEdit_P_Acc.setObjectName(_fromUtf8('lineEdit_P_Acc'))
        self.gridLayout_4.addWidget(self.lineEdit_P_Acc, 1, 1, 1, 1)
        
        # gun (accelerator) current text
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8('label_9'))
        self.gridLayout_4.addWidget(self.label_9, 2, 0, 1, 1)
        
        # target current number
        self.lineEdit_i_Tar = QtWidgets.QLineEdit(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_i_Tar.sizePolicy().hasHeightForWidth())
        self.lineEdit_i_Tar.setSizePolicy(sizePolicy)
        self.lineEdit_i_Tar.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_i_Tar.setFixedSize(edit_box_width, 20)    #added to make narrower
        self.lineEdit_i_Tar.setObjectName(_fromUtf8('lineEdit_i_Tar'))
        self.gridLayout_4.addWidget(self.lineEdit_i_Tar, 3, 1, 1, 1)
        
        # gun (accelerator) current number
        self.lineEdit_i_Acc = QtWidgets.QLineEdit(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_i_Acc.sizePolicy().hasHeightForWidth())
        self.lineEdit_i_Acc.setSizePolicy(sizePolicy)
        self.lineEdit_i_Acc.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_i_Acc.setFixedSize(edit_box_width, 20)    #added to make narrower
        self.lineEdit_i_Acc.setObjectName(_fromUtf8('lineEdit_i_Acc'))
        self.gridLayout_4.addWidget(self.lineEdit_i_Acc, 2, 1, 1, 1)
        
        # target current text
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8('label_10'))
        self.gridLayout_4.addWidget(self.label_10, 3, 0, 1, 1)
        
        # measurable parameters text
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setWordWrap(True)      # added
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)   # added
        font = QtGui.QFont()
        font.setFamily(_fromUtf8('Helvetica'))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8('label_7'))
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 2)
        
        self.gridLayout_13.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_7, 0, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_5, 0, 0, 1, 1)
        
        # other parameters frame (frame_6) 4x4
        self.frame_6 = QtWidgets.QFrame(self.frame_TL)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8('frame_6'))
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_12.setContentsMargins(12,12,12,12)
        self.gridLayout_12.setObjectName(_fromUtf8('gridLayout_12'))
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8('gridLayout_2'))
        # Grid voltage text
        self.label_11 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8('label_11'))
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        # Bending magnet energy number
        # CHECK THIS variable; name doesn't make sense
        self.lineEdit_T_Av_Tar = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_T_Av_Tar.sizePolicy().hasHeightForWidth())
        self.lineEdit_T_Av_Tar.setSizePolicy(sizePolicy)
        self.lineEdit_T_Av_Tar.setFixedSize(edit_box_width, 20)    #added to make narrower
        self.lineEdit_T_Av_Tar.setObjectName(_fromUtf8('lineEdit_T_Av_Tar'))
        self.gridLayout_2.addWidget(self.lineEdit_T_Av_Tar, 1, 3, 1, 1)    # was 3
        # Pulse width text; commented out attempt to give more space
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        #sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        #self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8('label_3'))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        # Pulse width number
        self.lineEdit_Tau = QtWidgets.QLineEdit(self.frame_6)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.lineEdit_Tau.sizePolicy().hasHeightForWidth())
        # self.lineEdit_Tau.setSizePolicy(sizePolicy)
        self.lineEdit_Tau.setFixedSize(edit_box_width, 20)    #added to make narrower
        self.lineEdit_Tau.setObjectName(_fromUtf8('lineEdit_Tau'))
        self.gridLayout_2.addWidget(self.lineEdit_Tau, 1, 1, 1, 1)
        # Gun voltage number
        self.lineEdit_v_Gun = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_v_Gun.sizePolicy().hasHeightForWidth())
        self.lineEdit_v_Gun.setSizePolicy(sizePolicy)
        self.lineEdit_v_Gun.setFixedSize(edit_box_width, 20)    #added to make narrower
        self.lineEdit_v_Gun.setObjectName(_fromUtf8('lineEdit_v_Gun'))
        self.gridLayout_2.addWidget(self.lineEdit_v_Gun, 2, 1, 1, 1)
        # Bending magnet energy text
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8('label_5'))
        self.gridLayout_2.addWidget(self.label_5, 1, 2, 1, 1)   # was at 2 and 1 wide
        # Gun voltage text
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8('label_4'))
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        # Accelerator energy text
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8('label_6'))
        self.gridLayout_2.addWidget(self.label_6, 2, 2, 1, 1)   # was at 2 and 1 wide
        # Accelerator energy number (according to 2,3 position)
        # CHECK THIS variable; name doesn't make sense
        self.lineEdit_T_Av_BMag = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_T_Av_BMag.sizePolicy().hasHeightForWidth())
        self.lineEdit_T_Av_BMag.setSizePolicy(sizePolicy)
        self.lineEdit_T_Av_BMag.setFixedSize(edit_box_width, 20)    #added to make narrower
        self.lineEdit_T_Av_BMag.setObjectName(_fromUtf8('lineEdit_T_Av_BMag'))
        self.gridLayout_2.addWidget(self.lineEdit_T_Av_BMag, 2, 3, 1, 1)   # was 3
        # Grid voltage number
        self.lineEdit_v_Grid = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_v_Grid.sizePolicy().hasHeightForWidth())
        self.lineEdit_v_Grid.setSizePolicy(sizePolicy)
        self.lineEdit_v_Grid.setFixedSize(edit_box_width, 20)    #added to make narrower
        self.lineEdit_v_Grid.setObjectName(_fromUtf8('lineEdit_v_Grid'))
        self.gridLayout_2.addWidget(self.lineEdit_v_Grid, 3, 1, 1, 1)
        # Beam power number
        self.lineEdit_P_Beam_Acc = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_P_Beam_Acc.sizePolicy().hasHeightForWidth())
        self.lineEdit_P_Beam_Acc.setSizePolicy(sizePolicy)
        self.lineEdit_P_Beam_Acc.setFixedSize(edit_box_width, 20)    #added to make narrower
        self.lineEdit_P_Beam_Acc.setObjectName(_fromUtf8('lineEdit_P_Beam_Acc'))
        self.gridLayout_2.addWidget(self.lineEdit_P_Beam_Acc, 3, 3, 1, 1)   # was 3
        # Beam power text
        self.label_12 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8('label_12'))
        self.gridLayout_2.addWidget(self.label_12, 3, 2, 1, 1)   # was at 2 and 1 wide
        # Bending magnet current text
        self.label_13 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8('label_13'))
        self.gridLayout_2.addWidget(self.label_13, 4, 0, 1, 1)
        # Bending magnet current number
        self.lineEdit_i_Coil_BMag = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_i_Coil_BMag.sizePolicy().hasHeightForWidth())
        self.lineEdit_i_Coil_BMag.setSizePolicy(sizePolicy)
        self.lineEdit_i_Coil_BMag.setFixedSize(edit_box_width, 20)    #added to make narrower
        self.lineEdit_i_Coil_BMag.setObjectName(_fromUtf8('lineEdit_i_Coil_BMag'))
        self.gridLayout_2.addWidget(self.lineEdit_i_Coil_BMag, 4, 1, 1, 1)
        # Accelerator efficiency number
        self.lineEdit_Eff_Acc = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Eff_Acc.sizePolicy().hasHeightForWidth())
        self.lineEdit_Eff_Acc.setSizePolicy(sizePolicy)
        self.lineEdit_Eff_Acc.setFixedSize(edit_box_width, 20)    #added to make narrower
        self.lineEdit_Eff_Acc.setObjectName(_fromUtf8('lineEdit_Eff_Acc'))
        self.gridLayout_2.addWidget(self.lineEdit_Eff_Acc, 4, 3, 1, 1)  # was 3
        # Accelerator efficiency text
        self.label_17 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8('label_17'))
        self.gridLayout_2.addWidget(self.label_17, 4, 2, 1, 1)   # was at 2 and 1 wide
        # Other parameters text
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8('Helvetica'))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8('label_2'))
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 2)   # changed to 0,1 to center text
        self.gridLayout_12.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_6, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        #self.gridLayout.addWidget(self.frame_TL, 0, 0, 1, 1)
        self.topRow.addWidget(self.frame_TL)
        
        # top right frame
        self.frame_TR = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)  # was 0
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_TR.sizePolicy().hasHeightForWidth())
        self.frame_TR.setSizePolicy(sizePolicy)
        #self.frame_TR.setMinimumSize(QtCore.QSize(0, 0))    # added
        self.frame_TR.setMaximumSize(QtCore.QSize(300, 300))    # was 380, 300; does make it narrower
        self.frame_TR.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TR.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_TR.setObjectName(_fromUtf8('frame_TR'))
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_TR)
        self.gridLayout_10.setObjectName(_fromUtf8('gridLayout_10'))
        self.label = QtWidgets.QLabel(self.frame_TR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText(_fromUtf8(''))
        # changed image and scaled it properly
        #self.label.setPixmap(QtGui.QPixmap(_fromUtf8('resources/images/The_805_MHz_side-couple_cavities_cropped.jpg')))
        #self.label.setScaledContents(True)
        pixmap = QtGui.QPixmap(_fromUtf8('resources/images/The_805_MHz_side-couple_cavities_cropped.jpg')).scaled(250, 300, QtCore.Qt.KeepAspectRatio)
        self.label.setPixmap(pixmap)
        self.label.setObjectName(_fromUtf8('label'))
        # added tooltip
        self.label.setToolTip('https://upload.wikimedia.org/wikipedia/commons/0/0c/The_805_MHz_side-couple_cavities.jpg')
        self.gridLayout_10.addWidget(self.label, 0, 0, 1, 1)
        #self.gridLayout.addWidget(self.frame_TR, 0, 1, 1, 1)
        self.topRow.addWidget(self.frame_TR)
        
        # bottom right frame
        self.frame_BR = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)  # was 0
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_BR.sizePolicy().hasHeightForWidth())
        self.frame_BR.setSizePolicy(sizePolicy)
        self.frame_BR.setMinimumSize(QtCore.QSize(0, 0))    # 400 was 0,320 before
        self.frame_BR.setMaximumSize(QtCore.QSize(600, 320))
        self.frame_BR.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_BR.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_BR.setObjectName(_fromUtf8('frame_BR'))
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_BR)
        self.gridLayout_9.setContentsMargins(6,6,6,6)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName(_fromUtf8('gridLayout_9'))
        self.gridLayout_BR = QtWidgets.QGridLayout()
        self.gridLayout_BR.setObjectName(_fromUtf8('gridLayout_BR'))
        self.gridLayout_9.addLayout(self.gridLayout_BR, 0, 0, 1, 1)
        #self.gridLayout.addWidget(self.frame_BR, 2, 1, 1, 1)
        # self.bottomRow.addWidget(self.frame_BR) moved below to maintain correct order
        
        # bottom left frame
        self.frame_BL = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_BL.sizePolicy().hasHeightForWidth())
        self.frame_BL.setSizePolicy(sizePolicy)
        self.frame_BL.setMinimumSize(QtCore.QSize(350, 0))    # was 390, 320
        self.frame_BL.setMaximumSize(QtCore.QSize(390, 320))
        self.frame_BL.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_BL.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_BL.setObjectName(_fromUtf8('frame_BL'))
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_BL)
        self.gridLayout_8.setContentsMargins(6,6,6,6)
        self.gridLayout_8.setObjectName(_fromUtf8('gridLayout_8'))
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName(_fromUtf8('gridLayout_14'))
        self.frame_8 = QtWidgets.QFrame(self.frame_BL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8('frame_8'))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout.setContentsMargins(0,0,0,0)
        self.horizontalLayout.setObjectName(_fromUtf8('horizontalLayout'))
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8('groupBox_4'))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName(_fromUtf8('verticalLayout_4'))
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8('label_14'))
        self.verticalLayout_4.addWidget(self.label_14)
        self.comboBox_VDiv_AChan = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_VDiv_AChan.sizePolicy().hasHeightForWidth())
        self.comboBox_VDiv_AChan.setSizePolicy(sizePolicy)
        self.comboBox_VDiv_AChan.setObjectName(_fromUtf8('comboBox_VDiv_AChan'))
        self.comboBox_VDiv_AChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_AChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_AChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_AChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_AChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_AChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_AChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_AChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_AChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_AChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_AChan.addItem(_fromUtf8(''))
        self.verticalLayout_4.addWidget(self.comboBox_VDiv_AChan)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8('groupBox_3'))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName(_fromUtf8('verticalLayout'))
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8('label_15'))
        self.verticalLayout.addWidget(self.label_15)
        self.comboBox_VDiv_BChan = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_VDiv_BChan.sizePolicy().hasHeightForWidth())
        self.comboBox_VDiv_BChan.setSizePolicy(sizePolicy)
        self.comboBox_VDiv_BChan.setObjectName(_fromUtf8('comboBox_VDiv_BChan'))
        self.comboBox_VDiv_BChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_BChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_BChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_BChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_BChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_BChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_BChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_BChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_BChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_BChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_BChan.addItem(_fromUtf8(''))
        self.verticalLayout.addWidget(self.comboBox_VDiv_BChan)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8('groupBox_5'))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setObjectName(_fromUtf8('verticalLayout_2'))
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8('label_16'))
        self.verticalLayout_2.addWidget(self.label_16)
        self.comboBox_TDiv = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_TDiv.sizePolicy().hasHeightForWidth())
        self.comboBox_TDiv.setSizePolicy(sizePolicy)
        self.comboBox_TDiv.setObjectName(_fromUtf8('comboBox_TDiv'))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.verticalLayout_2.addWidget(self.comboBox_TDiv)
        self.horizontalLayout.addWidget(self.groupBox_5)
        self.gridLayout_14.addWidget(self.frame_8, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_BL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setObjectName(_fromUtf8('frame'))
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_16.setContentsMargins(0,0,0,0)
        self.gridLayout_16.setObjectName(_fromUtf8('gridLayout_16'))
        self.gridLayout_scope = QtWidgets.QGridLayout()
        self.gridLayout_scope.setObjectName(_fromUtf8('gridLayout_scope'))
        self.gridLayout_16.addLayout(self.gridLayout_scope, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_14, 1, 0, 1, 1)
        #self.gridLayout.addWidget(self.frame_BL, 2, 0, 1, 1)
        #self.gridLayout_6.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.bottomRow.addWidget(self.frame_BL)
        self.bottomRow.addWidget(self.frame_BR)
        #self.gridLayout_6.addLayout(topRow, 0, 0, 1, 1)
        #self.gridLayout_6.addLayout(bottomRow, 1, 0, 1, 1)
        
        self.verticalStack.addLayout(self.topRow)
        self.verticalStack.addLayout(self.bottomRow)
        
        self.retranslateUi(Form)
        self.comboBox_VDiv_AChan.setCurrentIndex(8)
        self.comboBox_VDiv_BChan.setCurrentIndex(8)
        self.comboBox_TDiv.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate('Form', 'Accelerator', None))
        self.groupBox_ChB.setTitle(_translate('Form', 'Channel B', None))
        self.groupBox_ChA.setTitle(_translate('Form', 'Channel A', None))
        self.label_8.setText(_translate('Form', 'RF Power [MW]', None))
        self.lineEdit_P_Acc.setText(_translate('Form', '0', None))
        self.label_9.setText(_translate('Form', 'Gun Current [mA]', None))
        self.lineEdit_i_Tar.setText(_translate('Form', '0', None))
        self.lineEdit_i_Acc.setText(_translate('Form', '0', None))
        self.label_10.setText(_translate('Form', 'Target Current [mA]', None))
        self.label_7.setText(_translate('Form', 'Parameters Measurable on Oscilloscope', None))
        self.label_11.setText(_translate('Form', 'Grid Voltage [V]', None))
        self.lineEdit_T_Av_Tar.setText(_translate('Form', '0', None))
        self.label_3.setText(_translate('Form', 'Pulse Width [\u00B5s]', None))
        self.lineEdit_Tau.setText(_translate('Form', '0', None))
        self.lineEdit_v_Gun.setText(_translate('Form', '0', None))
        self.label_5.setText(_translate('Form', 'Bending Magnet E [MeV]', None))
        self.label_4.setText(_translate('Form', 'Gun Voltage [kV]', None))
        self.label_6.setText(_translate('Form', 'Accelerator E [MeV]', None))
        self.lineEdit_T_Av_BMag.setText(_translate('Form', '0', None))
        self.lineEdit_v_Grid.setText(_translate('Form', '0', None))
        self.lineEdit_P_Beam_Acc.setText(_translate('Form', '0', None))
        self.label_12.setText(_translate('Form', 'Beam Power [MW]', None))
        self.label_13.setText(_translate('Form', 'Bending Magnet I [A]', None))
        self.lineEdit_i_Coil_BMag.setText(_translate('Form', '0', None))
        self.lineEdit_Eff_Acc.setText(_translate('Form', '0', None))
        self.label_17.setText(_translate('Form', 'Accelerator Efficiency [%]', None))
        self.label_2.setText(_translate('Form', 'Other Parameters', None))
        self.groupBox_4.setTitle(_translate('Form', 'Channel A', None))
        self.label_14.setText(_translate('Form', 'V/Div', None))
        self.comboBox_VDiv_AChan.setItemText(0, _translate('Form', '5mV', None))
        self.comboBox_VDiv_AChan.setItemText(1, _translate('Form', '10mV', None))
        self.comboBox_VDiv_AChan.setItemText(2, _translate('Form', '20mV', None))
        self.comboBox_VDiv_AChan.setItemText(3, _translate('Form', '50mV', None))
        self.comboBox_VDiv_AChan.setItemText(4, _translate('Form', '100mV', None))
        self.comboBox_VDiv_AChan.setItemText(5, _translate('Form', '200mV', None))
        self.comboBox_VDiv_AChan.setItemText(6, _translate('Form', '500mV', None))
        self.comboBox_VDiv_AChan.setItemText(7, _translate('Form', '1V', None))
        self.comboBox_VDiv_AChan.setItemText(8, _translate('Form', '2V', None))
        self.comboBox_VDiv_AChan.setItemText(9, _translate('Form', '5V', None))
        self.comboBox_VDiv_AChan.setItemText(10, _translate('Form', '10V', None))
        self.groupBox_3.setTitle(_translate('Form', 'Channel B', None))
        self.label_15.setText(_translate('Form', 'V/Div', None))
        self.comboBox_VDiv_BChan.setItemText(0, _translate('Form', '5mV', None))
        self.comboBox_VDiv_BChan.setItemText(1, _translate('Form', '10mV', None))
        self.comboBox_VDiv_BChan.setItemText(2, _translate('Form', '20mV', None))
        self.comboBox_VDiv_BChan.setItemText(3, _translate('Form', '50mV', None))
        self.comboBox_VDiv_BChan.setItemText(4, _translate('Form', '100mV', None))
        self.comboBox_VDiv_BChan.setItemText(5, _translate('Form', '200mV', None))
        self.comboBox_VDiv_BChan.setItemText(6, _translate('Form', '500mV', None))
        self.comboBox_VDiv_BChan.setItemText(7, _translate('Form', '1V', None))
        self.comboBox_VDiv_BChan.setItemText(8, _translate('Form', '2V', None))
        self.comboBox_VDiv_BChan.setItemText(9, _translate('Form', '5V', None))
        self.comboBox_VDiv_BChan.setItemText(10, _translate('Form', '10V', None))
        self.groupBox_5.setTitle(_translate('Form', 'Time', None))
        self.label_16.setText(_translate('Form', 'T/Div', None))
        self.comboBox_TDiv.setItemText(0, _translate('Form', '1\u00B5s', None))
        self.comboBox_TDiv.setItemText(1, _translate('Form', '2\u00B5s', None))
        self.comboBox_TDiv.setItemText(2, _translate('Form', '5\u00B5s', None))
        self.comboBox_TDiv.setItemText(3, _translate('Form', '10\u00B5s', None))
        self.comboBox_TDiv.setItemText(4, _translate('Form', '20\u00B5s', None))
        self.comboBox_TDiv.setItemText(5, _translate('Form', '50\u00B5s', None))
        self.comboBox_TDiv.setItemText(6, _translate('Form', '100\u00B5s', None))
        self.comboBox_TDiv.setItemText(7, _translate('Form', '200\u00B5s', None))
        self.comboBox_TDiv.setItemText(8, _translate('Form', '500\u00B5s', None))
        self.comboBox_TDiv.setItemText(9, _translate('Form', '1ms', None))
        self.comboBox_TDiv.setItemText(10, _translate('Form', '2ms', None))
        self.comboBox_TDiv.setItemText(11, _translate('Form', '5ms', None))
        self.comboBox_TDiv.setItemText(12, _translate('Form', '10ms', None))
        self.comboBox_TDiv.setItemText(13, _translate('Form', '20ms', None))
        self.comboBox_TDiv.setItemText(14, _translate('Form', '50ms', None))
        self.comboBox_TDiv.setItemText(15, _translate('Form', '100ms', None))
        self.comboBox_TDiv.setItemText(16, _translate('Form', '200ms', None))
        return

