# uncompyle6 version 3.9.0
# Python bytecode version base 2.7 (62211)
# Decompiled from: Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)]
# Embedded file name: views\simacKlystronWidget.pyc
# Compiled at: 2016-09-20 08:28:13
from PyQt5 import QtCore, QtGui, QtWidgets
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:

    def _fromUtf8(s):
        return s


try:
    _encoding = QtGui.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)


except AttributeError:

    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)


class Ui_Form(object):

    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8('Form'))
        Form.resize(800, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(800, 650))
        Form.setMaximumSize(QtCore.QSize(800, 650))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Form.setPalette(palette)
        self.gridLayout_6 = QtWidgets.QGridLayout(Form)
        self.gridLayout_6.setObjectName(_fromUtf8('gridLayout_6'))
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName(_fromUtf8('gridLayout'))
        
        # top right frame
        self.frame_TR = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_TR.sizePolicy().hasHeightForWidth())
        self.frame_TR.setSizePolicy(sizePolicy)
        self.frame_TR.setMaximumSize(QtCore.QSize(360, 300))
        self.frame_TR.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TR.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_TR.setObjectName(_fromUtf8('frame_TR'))
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_TR)
        #self.gridLayout_10.setMargin(6)
        #setMargin is obsolete; replaced with setContentsMargins
        self.gridLayout_10.setContentsMargins(6,6,6,6)
        self.gridLayout_10.setObjectName(_fromUtf8('gridLayout_10'))
        self.label = QtWidgets.QLabel(self.frame_TR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText(_fromUtf8(''))
        # changed image and scaled it properly
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8('resources/images/Klystron.png')).scaled(self.label.size()*4, 2, QtCore.Qt.SmoothTransformation))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8('label'))
        # added tooltip
        self.label.setToolTip('https://en.wikipedia.org/wiki/File:Klystron.enp.gif')
        self.gridLayout_10.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_TR, 0, 1, 1, 1)
        
        # bottom right frame
        self.frame_BR = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_BR.sizePolicy().hasHeightForWidth())
        self.frame_BR.setSizePolicy(sizePolicy)
        self.frame_BR.setMinimumSize(QtCore.QSize(0, 310))
        self.frame_BR.setMaximumSize(QtCore.QSize(400, 310))
        self.frame_BR.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_BR.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_BR.setObjectName(_fromUtf8('frame_BR'))
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_BR)
        self.gridLayout_9.setContentsMargins(6,6,6,6)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName(_fromUtf8('gridLayout_9'))
        self.gridLayout_BR = QtWidgets.QGridLayout()
        self.gridLayout_BR.setContentsMargins(6,6,6,6)
        self.gridLayout_BR.setObjectName(_fromUtf8('gridLayout_BR'))
        self.gridLayout_9.addLayout(self.gridLayout_BR, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_BR, 2, 1, 1, 1)
        
        # bottom left frame
        self.frame_BL = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_BL.sizePolicy().hasHeightForWidth())
        self.frame_BL.setSizePolicy(sizePolicy)
        self.frame_BL.setMinimumSize(QtCore.QSize(400, 310))
        self.frame_BL.setMaximumSize(QtCore.QSize(400, 310))
        self.frame_BL.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_BL.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_BL.setObjectName(_fromUtf8('frame_BL'))
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_BL)
        self.gridLayout_8.setContentsMargins(6,6,6,6)
        self.gridLayout_8.setObjectName(_fromUtf8('gridLayout_8'))
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName(_fromUtf8('gridLayout_15'))
        self.frame = QtWidgets.QFrame(self.frame_BL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8('frame'))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0,0,0,0)
        self.horizontalLayout_3.setObjectName(_fromUtf8('horizontalLayout_3'))
        self.gridLayout_scope = QtWidgets.QGridLayout()
        self.gridLayout_scope.setObjectName(_fromUtf8('gridLayout_scope'))
        self.horizontalLayout_3.addLayout(self.gridLayout_scope)
        self.gridLayout_15.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame_BL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8('frame_8'))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout.setObjectName(_fromUtf8('horizontalLayout'))
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8('groupBox_4'))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName(_fromUtf8('verticalLayout_4'))
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8('label_14'))
        self.verticalLayout_4.addWidget(self.label_14)
        self.comboBox_VDiv_AChan = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_VDiv_AChan.setObjectName(_fromUtf8('comboBox_VDiv_AChan'))
        self.comboBox_VDiv_AChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_AChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_AChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_AChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_AChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_AChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_AChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_AChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_AChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_AChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_AChan.addItem(_fromUtf8(''))
        self.verticalLayout_4.addWidget(self.comboBox_VDiv_AChan)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8('groupBox_3'))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName(_fromUtf8('verticalLayout'))
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8('label_15'))
        self.verticalLayout.addWidget(self.label_15)
        self.comboBox_VDiv_BChan = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_VDiv_BChan.setObjectName(_fromUtf8('comboBox_VDiv_BChan'))
        self.comboBox_VDiv_BChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_BChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_BChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_BChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_BChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_BChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_BChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_BChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_BChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_BChan.addItem(_fromUtf8(''))
        self.comboBox_VDiv_BChan.addItem(_fromUtf8(''))
        self.verticalLayout.addWidget(self.comboBox_VDiv_BChan)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8('groupBox_5'))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setObjectName(_fromUtf8('verticalLayout_2'))
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8('label_16'))
        self.verticalLayout_2.addWidget(self.label_16)
        self.comboBox_TDiv = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_TDiv.setObjectName(_fromUtf8('comboBox_TDiv'))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.comboBox_TDiv.addItem(_fromUtf8(''))
        self.verticalLayout_2.addWidget(self.comboBox_TDiv)
        self.horizontalLayout.addWidget(self.groupBox_5)
        self.gridLayout_15.addWidget(self.frame_8, 1, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_BL, 2, 0, 1, 1)
        
        # top left frame
        edit_box_width = 60     #hard coded width to make text fit
        self.frame_TL = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_TL.sizePolicy().hasHeightForWidth())
        self.frame_TL.setSizePolicy(sizePolicy)
        self.frame_TL.setMinimumSize(QtCore.QSize(400, 300))
        self.frame_TL.setMaximumSize(QtCore.QSize(400, 320))
        self.frame_TL.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_TL.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_TL.setLineWidth(1)
        self.frame_TL.setObjectName(_fromUtf8('frame_TL'))
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_TL)
        self.gridLayout_7.setContentsMargins(6,6,6,6)
        self.gridLayout_7.setObjectName(_fromUtf8('gridLayout_7'))
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName(_fromUtf8('gridLayout_5'))
        self.frame_5 = QtWidgets.QFrame(self.frame_TL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8('frame_5'))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setContentsMargins(3,3,3,3)
        self.horizontalLayout_2.setObjectName(_fromUtf8('horizontalLayout_2'))
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8('gridLayout_3'))
        
        # Measurable parameters frame
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8('frame_7'))
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_11.setContentsMargins(6, 0, 6, 0)
        self.gridLayout_11.setObjectName(_fromUtf8('gridLayout_11'))
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8('gridLayout_4'))
        
        # HVPS current text
        self.label_13 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8('label_13'))
        self.gridLayout_4.addWidget(self.label_13, 6, 0, 1, 1)
        
        # Klystron voltage text
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8('label_9'))
        self.gridLayout_4.addWidget(self.label_9, 2, 0, 1, 1)
        
        # PFN voltage number
        self.lineEdit_v_PFN = QtWidgets.QLineEdit(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_v_PFN.sizePolicy().hasHeightForWidth())
        self.lineEdit_v_PFN.setSizePolicy(sizePolicy)
        #self.lineEdit_v_PFN.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_v_PFN.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lineEdit_v_PFN.setFixedSize(edit_box_width, 20)    #added to make narrower
        self.lineEdit_v_PFN.setObjectName(_fromUtf8('lineEdit_v_PFN'))
        self.gridLayout_4.addWidget(self.lineEdit_v_PFN, 5, 1, 1, 1)
        
        # Klystron voltage number
        self.lineEdit_v_Kly = QtWidgets.QLineEdit(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_v_Kly.sizePolicy().hasHeightForWidth())
        self.lineEdit_v_Kly.setSizePolicy(sizePolicy)
        #self.lineEdit_v_Kly.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_v_Kly.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lineEdit_v_Kly.setFixedSize(edit_box_width, 20)    #added to make narrower
        self.lineEdit_v_Kly.setObjectName(_fromUtf8('lineEdit_v_Kly'))
        self.gridLayout_4.addWidget(self.lineEdit_v_Kly, 2, 1, 1, 1)
        
        # RF power out label
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8('label_10'))
        self.gridLayout_4.addWidget(self.label_10, 3, 0, 1, 1)
        
        # PFN voltage text
        self.label_12 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8('label_12'))
        self.gridLayout_4.addWidget(self.label_12, 5, 0, 1, 1)
        
        # Klystron current text
        self.label_11 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8('label_11'))
        self.gridLayout_4.addWidget(self.label_11, 4, 0, 1, 1)
        
        # RF power out number
        self.lineEdit_P_Acc = QtWidgets.QLineEdit(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_P_Acc.sizePolicy().hasHeightForWidth())
        self.lineEdit_P_Acc.setSizePolicy(sizePolicy)
        #self.lineEdit_P_Acc.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_P_Acc.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lineEdit_P_Acc_Tar.setFixedSize(edit_box_width, 20)    #added to make narrower
        self.lineEdit_P_Acc.setObjectName(_fromUtf8('lineEdit_P_Acc'))
        self.gridLayout_4.addWidget(self.lineEdit_P_Acc, 3, 1, 1, 1)
        
        # RF power in text
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8('label_8'))
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        
        # Klystron current number
        self.lineEdit_i_Kly = QtWidgets.QLineEdit(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_i_Kly.sizePolicy().hasHeightForWidth())
        self.lineEdit_i_Kly.setSizePolicy(sizePolicy)
        #self.lineEdit_i_Kly.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_i_Kly.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lineEdit_i_Kly.setFixedSize(edit_box_width, 20)    #added to make narrower
        self.lineEdit_i_Kly.setObjectName(_fromUtf8('lineEdit_i_Kly'))
        self.gridLayout_4.addWidget(self.lineEdit_i_Kly, 4, 1, 1, 1)
        
        # RF power in number
        self.lineEdit_P_AC_Kly = QtWidgets.QLineEdit(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_P_AC_Kly.sizePolicy().hasHeightForWidth())
        self.lineEdit_P_AC_Kly.setSizePolicy(sizePolicy)
        #self.lineEdit_P_AC_Kly.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_P_AC_Kly.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lineEdit_P_AC_Kly.setFixedSize(edit_box_width, 20)    #added to make narrower
        self.lineEdit_P_AC_Kly.setObjectName(_fromUtf8('lineEdit_P_AC_Kly'))
        self.gridLayout_4.addWidget(self.lineEdit_P_AC_Kly, 1, 1, 1, 1)
        
        # HVPS current number
        self.lineEdit_I_HVPS = QtWidgets.QLineEdit(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_I_HVPS.sizePolicy().hasHeightForWidth())
        self.lineEdit_I_HVPS.setSizePolicy(sizePolicy)
        #self.lineEdit_I_HVPS.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_I_HVPS.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lineEdit_I_HVPS.setFixedSize(edit_box_width, 20)    #added to make narrower
        self.lineEdit_I_HVPS.setObjectName(_fromUtf8('lineEdit_I_HVPS'))
        self.gridLayout_4.addWidget(self.lineEdit_I_HVPS, 6, 1, 1, 1)
        
        # measurable parameters text
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8('Helvetica'))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8('label_7'))
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 2)
        
        
        self.gridLayout_11.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_7, 0, 0, 1, 1)
        
        # Channel A box
        self.groupBox_ChA = QtWidgets.QGroupBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_ChA.sizePolicy().hasHeightForWidth())
        self.groupBox_ChA.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_ChA.setFont(font)
        self.groupBox_ChA.setFlat(False)
        self.groupBox_ChA.setCheckable(False)
        self.groupBox_ChA.setObjectName(_fromUtf8('groupBox_ChA'))
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_ChA)
        self.gridLayout_13.setContentsMargins(6,6,6,6)
        self.gridLayout_13.setObjectName(_fromUtf8('gridLayout_13'))
        self.radioButton_ChA_1 = QtWidgets.QRadioButton(self.groupBox_ChA)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_ChA_1.sizePolicy().hasHeightForWidth())
        self.radioButton_ChA_1.setSizePolicy(sizePolicy)
        self.radioButton_ChA_1.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_ChA_1.setFont(font)
        self.radioButton_ChA_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_ChA_1.setText(_fromUtf8(''))
        self.radioButton_ChA_1.setChecked(True)
        self.radioButton_ChA_1.setObjectName(_fromUtf8('radioButton_ChA_1'))
        self.gridLayout_13.addWidget(self.radioButton_ChA_1, 0, 0, 1, 1)
        self.radioButton_ChA_3 = QtWidgets.QRadioButton(self.groupBox_ChA)
        self.radioButton_ChA_3.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_ChA_3.setFont(font)
        self.radioButton_ChA_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_ChA_3.setText(_fromUtf8(''))
        self.radioButton_ChA_3.setObjectName(_fromUtf8('radioButton_ChA_3'))
        self.gridLayout_13.addWidget(self.radioButton_ChA_3, 2, 0, 1, 1)
        self.radioButton_ChA_2 = QtWidgets.QRadioButton(self.groupBox_ChA)
        self.radioButton_ChA_2.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_ChA_2.setFont(font)
        self.radioButton_ChA_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_ChA_2.setText(_fromUtf8(''))
        self.radioButton_ChA_2.setObjectName(_fromUtf8('radioButton_ChA_2'))
        self.gridLayout_13.addWidget(self.radioButton_ChA_2, 1, 0, 1, 1)
        self.radioButton_ChA_5 = QtWidgets.QRadioButton(self.groupBox_ChA)
        self.radioButton_ChA_5.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_ChA_5.setFont(font)
        self.radioButton_ChA_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_ChA_5.setText(_fromUtf8(''))
        self.radioButton_ChA_5.setObjectName(_fromUtf8('radioButton_ChA_5'))
        self.gridLayout_13.addWidget(self.radioButton_ChA_5, 4, 0, 1, 1)
        self.radioButton_ChA_4 = QtWidgets.QRadioButton(self.groupBox_ChA)
        self.radioButton_ChA_4.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_ChA_4.setFont(font)
        self.radioButton_ChA_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_ChA_4.setText(_fromUtf8(''))
        self.radioButton_ChA_4.setObjectName(_fromUtf8('radioButton_ChA_4'))
        self.gridLayout_13.addWidget(self.radioButton_ChA_4, 3, 0, 1, 1)
        self.radioButton_ChA_6 = QtWidgets.QRadioButton(self.groupBox_ChA)
        self.radioButton_ChA_6.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_ChA_6.setFont(font)
        self.radioButton_ChA_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_ChA_6.setText(_fromUtf8(''))
        self.radioButton_ChA_6.setObjectName(_fromUtf8('radioButton_ChA_6'))
        self.gridLayout_13.addWidget(self.radioButton_ChA_6, 5, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_ChA, 0, 1, 1, 1)
        self.groupBox_ChB = QtWidgets.QGroupBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_ChB.sizePolicy().hasHeightForWidth())
        self.groupBox_ChB.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_ChB.setFont(font)
        self.groupBox_ChB.setFlat(False)
        self.groupBox_ChB.setCheckable(False)
        self.groupBox_ChB.setObjectName(_fromUtf8('groupBox_ChB'))
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_ChB)
        self.gridLayout_14.setContentsMargins(6,6,6,6)
        self.gridLayout_14.setObjectName(_fromUtf8('gridLayout_14'))
        self.radioButton_ChB_4 = QtWidgets.QRadioButton(self.groupBox_ChB)
        self.radioButton_ChB_4.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_ChB_4.setFont(font)
        self.radioButton_ChB_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_ChB_4.setText(_fromUtf8(''))
        self.radioButton_ChB_4.setObjectName(_fromUtf8('radioButton_ChB_4'))
        self.gridLayout_14.addWidget(self.radioButton_ChB_4, 3, 0, 1, 1)
        self.radioButton_ChB_1 = QtWidgets.QRadioButton(self.groupBox_ChB)
        self.radioButton_ChB_1.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_ChB_1.setFont(font)
        self.radioButton_ChB_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_ChB_1.setText(_fromUtf8(''))
        self.radioButton_ChB_1.setChecked(True)
        self.radioButton_ChB_1.setObjectName(_fromUtf8('radioButton_ChB_1'))
        self.gridLayout_14.addWidget(self.radioButton_ChB_1, 0, 0, 1, 1)
        self.radioButton_ChB_5 = QtWidgets.QRadioButton(self.groupBox_ChB)
        self.radioButton_ChB_5.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_ChB_5.setFont(font)
        self.radioButton_ChB_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_ChB_5.setText(_fromUtf8(''))
        self.radioButton_ChB_5.setObjectName(_fromUtf8('radioButton_ChB_5'))
        self.gridLayout_14.addWidget(self.radioButton_ChB_5, 4, 0, 1, 1)
        self.radioButton_ChB_3 = QtWidgets.QRadioButton(self.groupBox_ChB)
        self.radioButton_ChB_3.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_ChB_3.setFont(font)
        self.radioButton_ChB_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_ChB_3.setText(_fromUtf8(''))
        self.radioButton_ChB_3.setObjectName(_fromUtf8('radioButton_ChB_3'))
        self.gridLayout_14.addWidget(self.radioButton_ChB_3, 2, 0, 1, 1)
        self.radioButton_ChB_2 = QtWidgets.QRadioButton(self.groupBox_ChB)
        self.radioButton_ChB_2.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_ChB_2.setFont(font)
        self.radioButton_ChB_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_ChB_2.setText(_fromUtf8(''))
        self.radioButton_ChB_2.setObjectName(_fromUtf8('radioButton_ChB_2'))
        self.gridLayout_14.addWidget(self.radioButton_ChB_2, 1, 0, 1, 1)
        self.radioButton_ChB_6 = QtWidgets.QRadioButton(self.groupBox_ChB)
        self.radioButton_ChB_6.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_ChB_6.setFont(font)
        self.radioButton_ChB_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_ChB_6.setText(_fromUtf8(''))
        self.radioButton_ChB_6.setObjectName(_fromUtf8('radioButton_ChB_6'))
        self.gridLayout_14.addWidget(self.radioButton_ChB_6, 5, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_ChB, 0, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.gridLayout_5.addWidget(self.frame_5, 0, 0, 1, 1)
        
        # Other parameters frame
        self.frame_6 = QtWidgets.QFrame(self.frame_TL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8('frame_6'))
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_12.setContentsMargins(3,3,3,3)
        self.gridLayout_12.setObjectName(_fromUtf8('gridLayout_12'))
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8('gridLayout_2'))
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8('label_4'))
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_k_Kly = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_k_Kly.sizePolicy().hasHeightForWidth())
        self.lineEdit_k_Kly.setSizePolicy(sizePolicy)
        self.lineEdit_k_Kly.setObjectName(_fromUtf8('lineEdit_k_Kly'))
        self.gridLayout_2.addWidget(self.lineEdit_k_Kly, 2, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8('label_3'))
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8('label_6'))
        self.gridLayout_2.addWidget(self.label_6, 3, 2, 1, 1)
        self.lineEdit_Efficiency = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Efficiency.sizePolicy().hasHeightForWidth())
        self.lineEdit_Efficiency.setSizePolicy(sizePolicy)
        self.lineEdit_Efficiency.setObjectName(_fromUtf8('lineEdit_Efficiency'))
        self.gridLayout_2.addWidget(self.lineEdit_Efficiency, 3, 3, 1, 1)
        self.lineEdit_Omega = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Omega.sizePolicy().hasHeightForWidth())
        self.lineEdit_Omega.setSizePolicy(sizePolicy)
        self.lineEdit_Omega.setObjectName(_fromUtf8('lineEdit_Omega'))
        self.gridLayout_2.addWidget(self.lineEdit_Omega, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8('label_5'))
        self.gridLayout_2.addWidget(self.label_5, 2, 2, 1, 1)
        self.lineEdit_P_Kly_Refl = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_P_Kly_Refl.sizePolicy().hasHeightForWidth())
        self.lineEdit_P_Kly_Refl.setSizePolicy(sizePolicy)
        self.lineEdit_P_Kly_Refl.setObjectName(_fromUtf8('lineEdit_P_Kly_Refl'))
        self.gridLayout_2.addWidget(self.lineEdit_P_Kly_Refl, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8('Helvetica'))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8('label_2'))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 2)
        self.gridLayout_12.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_6, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_TL, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.retranslateUi(Form)
        self.comboBox_VDiv_AChan.setCurrentIndex(8)
        self.comboBox_VDiv_BChan.setCurrentIndex(8)
        self.comboBox_TDiv.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate('Form', 'Klystron', None))
        self.groupBox_4.setTitle(_translate('Form', 'Channel A', None))
        self.label_14.setText(_translate('Form', 'V/Div', None))
        self.comboBox_VDiv_AChan.setItemText(0, _translate('Form', '5mV', None))
        self.comboBox_VDiv_AChan.setItemText(1, _translate('Form', '10mV', None))
        self.comboBox_VDiv_AChan.setItemText(2, _translate('Form', '20mV', None))
        self.comboBox_VDiv_AChan.setItemText(3, _translate('Form', '50mV', None))
        self.comboBox_VDiv_AChan.setItemText(4, _translate('Form', '100mV', None))
        self.comboBox_VDiv_AChan.setItemText(5, _translate('Form', '200mV', None))
        self.comboBox_VDiv_AChan.setItemText(6, _translate('Form', '500mV', None))
        self.comboBox_VDiv_AChan.setItemText(7, _translate('Form', '1V', None))
        self.comboBox_VDiv_AChan.setItemText(8, _translate('Form', '2V', None))
        self.comboBox_VDiv_AChan.setItemText(9, _translate('Form', '5V', None))
        self.comboBox_VDiv_AChan.setItemText(10, _translate('Form', '10V', None))
        self.groupBox_3.setTitle(_translate('Form', 'Channel B', None))
        self.label_15.setText(_translate('Form', 'V/Div', None))
        self.comboBox_VDiv_BChan.setItemText(0, _translate('Form', '5mV', None))
        self.comboBox_VDiv_BChan.setItemText(1, _translate('Form', '10mV', None))
        self.comboBox_VDiv_BChan.setItemText(2, _translate('Form', '20mV', None))
        self.comboBox_VDiv_BChan.setItemText(3, _translate('Form', '50mV', None))
        self.comboBox_VDiv_BChan.setItemText(4, _translate('Form', '100mV', None))
        self.comboBox_VDiv_BChan.setItemText(5, _translate('Form', '200mV', None))
        self.comboBox_VDiv_BChan.setItemText(6, _translate('Form', '500mV', None))
        self.comboBox_VDiv_BChan.setItemText(7, _translate('Form', '1V', None))
        self.comboBox_VDiv_BChan.setItemText(8, _translate('Form', '2V', None))
        self.comboBox_VDiv_BChan.setItemText(9, _translate('Form', '5V', None))
        self.comboBox_VDiv_BChan.setItemText(10, _translate('Form', '10V', None))
        self.groupBox_5.setTitle(_translate('Form', 'Time', None))
        self.label_16.setText(_translate('Form', 'T/Div', None))
        self.comboBox_TDiv.setItemText(0, _translate('Form', '1us', None))
        self.comboBox_TDiv.setItemText(1, _translate('Form', '2us', None))
        self.comboBox_TDiv.setItemText(2, _translate('Form', '5us', None))
        self.comboBox_TDiv.setItemText(3, _translate('Form', '10us', None))
        self.comboBox_TDiv.setItemText(4, _translate('Form', '20us', None))
        self.comboBox_TDiv.setItemText(5, _translate('Form', '50us', None))
        self.comboBox_TDiv.setItemText(6, _translate('Form', '100us', None))
        self.comboBox_TDiv.setItemText(7, _translate('Form', '200us', None))
        self.comboBox_TDiv.setItemText(8, _translate('Form', '500us', None))
        self.comboBox_TDiv.setItemText(9, _translate('Form', '1ms', None))
        self.comboBox_TDiv.setItemText(10, _translate('Form', '2ms', None))
        self.comboBox_TDiv.setItemText(11, _translate('Form', '5ms', None))
        self.comboBox_TDiv.setItemText(12, _translate('Form', '10ms', None))
        self.comboBox_TDiv.setItemText(13, _translate('Form', '20ms', None))
        self.comboBox_TDiv.setItemText(14, _translate('Form', '50ms', None))
        self.comboBox_TDiv.setItemText(15, _translate('Form', '100ms', None))
        self.comboBox_TDiv.setItemText(16, _translate('Form', '200ms', None))
        self.label_13.setText(_translate('Form', 'HVPS I [A]', None))
        self.label_9.setText(_translate('Form', 'Kly V [kV]', None))
        self.lineEdit_v_PFN.setText(_translate('Form', '0', None))
        self.lineEdit_v_Kly.setText(_translate('Form', '0', None))
        self.label_10.setText(_translate('Form', 'RF Out [MW]', None))
        self.label_12.setText(_translate('Form', 'PFN V [kV]', None))
        self.label_11.setText(_translate('Form', 'Kly I [A]', None))
        self.lineEdit_P_Acc.setText(_translate('Form', '0', None))
        self.label_8.setText(_translate('Form', 'RF In [W]', None))
        self.lineEdit_i_Kly.setText(_translate('Form', '0', None))
        self.lineEdit_P_AC_Kly.setText(_translate('Form', '0', None))
        self.lineEdit_I_HVPS.setText(_translate('Form', '0', None))
        self.label_7.setText(_translate('Form', 'Measurable Parameters', None))
        self.groupBox_ChA.setTitle(_translate('Form', 'CH A', None))
        self.groupBox_ChB.setTitle(_translate('Form', 'CH B', None))
        self.label_4.setText(_translate('Form', 'PRefl [MW]', None))
        self.lineEdit_k_Kly.setText(_translate('Form', '0', None))
        self.label_3.setText(_translate('Form', 'RF Freq [MHz]', None))
        self.label_6.setText(_translate('Form', 'efficiency [%]', None))
        self.lineEdit_Efficiency.setText(_translate('Form', '0', None))
        self.lineEdit_Omega.setText(_translate('Form', '0', None))
        self.label_5.setText(_translate('Form', 'Gain [dB]', None))
        self.lineEdit_P_Kly_Refl.setText(_translate('Form', '0', None))
        self.label_2.setText(_translate('Form', 'Other Parameters', None))
        return
# okay decompiling simacKlystronWidget.pyc
